# Generated by Django 3.1.2 on 2020-10-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('version', models.CharField(max_length=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_expired', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('short_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.catalog')),
            ],
        ),
    ]
