# Generated by Django 3.1.2 on 2020-10-06 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201006_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='value',
        ),
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.CharField(default=datetime.date(2020, 10, 6), max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date_expired',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date_started',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='version',
            field=models.CharField(max_length=10, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='element',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
