version: '3'

services:

  api:
    image: api
    build: komtek-api/.
    command: python komtek-api/komtek/manage.py runserver
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./komtek-api.env