version: '3'

services:

  api:
    image: api
    build: komtek-api/.
    command: gunicorn komtek.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/komtek/komtek/static
    expose:
      - 8000
    env_file:
      - ./komtek-api.env

  nginx:
    build: nginx/.
    volumes:
      - static_volume:/usr/src/app/komtek/komtek/static
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  static_volume: