version: '3'

services:

  api:
    image: api
    build: komtek-api/.
    command: gunicorn komtek-api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./komtek-api/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./komtek-api.env
#     Uncomment if you want to use Postgres
#    depends_on:
#      - db

  nginx:
    build: nginx/.
    ports:
      - 1337:80
    depends_on:
      - api

#  db:
#    image: postgres:alpine
#    #volumes:
#    #  # Mounting a database in the host system so it's
#    #  # persistent through different containers
#      - ${HOME}postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - ./komtek-db.env