version: '3'

services:

  api:
    image: api
    build: komtek-api/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./komtek-api/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./komtek-api.env