version: '3'

services:

  api:
    image: api
    build: komtek-api/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./komtek-api/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./komtek-api.env
    depends_on:
      - db
      
  db:
    image: postgres:alpine
    #volumes:
    #  # Mounting a database in the host system so it's
    #  # persistent through different containers
    #  - ${HOME}postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./komtek-db.env