# Generated by Django 3.1.2 on 2020-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
