# Generated by Django 3.1.2 on 2020-10-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catalog_date_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='date_released',
        ),
        migrations.AddField(
            model_name='catalog',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('catalog', 'code')},
        ),
    ]
